<script>
	import Popup from './popup.svelte';
	let ideaButton;
	let idea = '';

	let ideas = [
		'Getting caught vibing, dancing, or acting weird in your room by a parent',
		'Getting rejected',
		'Blaming someone else for a fart',
		'Practicing kissing with a mirror',
		'Walking into a door, wall, or pole',
		'Pretending to be sick to avoid a social event',
		'Sleeping with a nightlight on',
		'Pretending to be someone else on the phone',
		'Asking someone out',
		'Being stood up on a date or outing',
		'Being forgotten somewhere by your parents',
		'Lying about someone to make yourself look better',
		'Cheating on an exam',
		'Being told you have B/O',
		'Having a crush on a teacher',
		"Doing something regrettable to get a crush's attention",
		'Lying about your age',
		'Going to a nude beach (not to watch 🤨)',
		'Getting a secret piercing',
		'Getting a secret tattoo (stick n poke counts)',
		'Failing a class',
		'Getting caught sleeping during class or a meeting',
		'Lying about yourself to look better',
		"Dating someone because you felt bad or couldn't say no",
		'Getting caught changing',
		'Going skinny-dipping',
		'Getting caught skinny-dipping',
		'Sneaking out of the house',
		"Trying to show off your singing 'skills'",
		'Getting rejected in front of a group',
		'Crying during class',
		'Talking to someone thinking they were someone else',
		"Calling a teacher or other adult 'mom' or 'dad'",
		'Sending a ✨spicy✨ photo or flashing someone',
		'Being asked out',
		'Being uninvited somewhere',
		'Being rude to someone to appeal to another person',
		'Making someone cry',
		'Betraying a friend to appeal to another',
		'Cheating on someone',
		"Watching all the ZNW videos (intense shame if you haven't >:( )",
		'Wishing to be someone else',
		'Going to the wrong house thinking it was yours',
		'Getting caught talking to yourself',
		'Trying to talk to an animal thinking they understood',
		'Believing in Santa Claus (past or present)',
		'Believing in the tooth fairy',
		'Dating someone who looks like a relative',
		'Walking around your house naked',
		'Buying an NFT or Crypto',
		"Forgetting someone's birthday",
		'Being grounded',
		'Having an imaginary friend',
		'Betraying a friend for $1 million',
		'Betraying a best friend for true happiness',
		'Sacrificing a stranger to fix a past mistake',
		'Sacrificing two strangers to save a loved one',
		'Living your life over again',
		'Knowing what everyone truly thinks about you',
		'The ability to tell who really loves you',
		'Risking your life to save another',
		'Thoughts on the existence of true justice',
		"Finding out how you're going to die",
		'Choosing to have specific memories erased',
		'Staying in a relationship you know will end in 5 years',
		"Working a high-paying job where you're never happy",
		"Working a low-paying job where you're always happy",
		'Bringing a loved one back with no memory of you',
		'Living without regrets',
		'Happiness with how your life turned out if it ended tomorrow',
		'Losing your eyesight to bring back a loved one',
		"Knowing ZNW's middle name",
		"Knowing ZNW's birthday",
		"Dating a friend's ex",
		"Using someone's insecurities against them",
		"Sacrificing your happiness for everyone else's",
		"Sacrificing your health for everyone else's",
		'Returning to someone who cheated on you',
		'Seeing a parent/guardian cry',
		'Writing a love poem',
		'Sharing lottery winnings with loved ones',
		'Ending world problems at the cost of your life',
		"Your younger self's opinion of you now",
		'Your feelings on spiders',
		'Standing in a toilet',
		'Breaking a bone',
		'Something embarassing in your search history',
		'Dying on an embarassing hill',
		'Throwing up in public',
		'Killing someone if there were no consequences',
		'Embarrassing things on your computer',
		"Lying saying 'I love you'",
		'Peeing in the shower',
		"Drinking everyone's urine to solve world problems",
		'Dating your boss for a promotion even if everyone hates you',
		'Waking up to neighbors being loud in bed',
		'Pulling an all-nighter',
		'Rice purity score',
		"Getting caught watching something you shouldn't have",
		'Being invited to a party',
		'Feeling like a conversation would be better without you',
		'Touching grass',
		'Having your heart broken',
		'Playing strip poker',
		'Using Omegle',
		'Running away from problems',
		'Kissing a picture of someone',
		'Being happy if you died tomorrow',
		'Motivation to wake up every day',
		"Having a 'friends with benefits' relationship",
		'Considering yourself superior to others',
		'Relationship with your parents',
		'Friends being more important than family',
		'Stealing something',
		'Thoughts on knife crime',
		'Believing people can change',
		'Being in trouble with the police',
		'Self-sabotaging',
		'Having a rice-purity score over 95',
		'Using iMovie to edit',
		'Using Discord light mode',
		'Light mode vs. Dark mode',
		'Hurting someone you loved',
		'Deleting search history to cover something up',
		'Picking up a call at 3am',
		'Crying yourself to sleep',
		'Faking an apology',
		'Faking an injury',
		'Faking something for attention',
		'Fear that everyone will leave you',
		'Laughing during a serious situation',
		'Hitting rock bottom',
		'Washing your asshole',
		'Wasting time on meaningless things',
		'Using Twitch light mode',
		'Subscribed to ZombieNW',
		'Subscribed to the UnFunny Podcast',
		'Believing in conspiracy theories',
		'Getting surgery',
		'Going to the emergency room',
		'Tripping over a curb in public',
		'Accidentally liking an old photo while stalking someone',
		'Posting a TikTok dance',
		"Being with someone else during a relationship 'break'",
		'Listening to ASMR',
		'Non-ironically using a pick-up line',
		'Keeping a diary',
		'Fear of the dark',
		'Believing in aliens',
		'Fear that people can read your mind',
		'Failing to cut your own hair',
		'Touching your toes',
		'Whistling',
		'Regretting letting someone go',
		'Liking Country music un-ironically',
		'Thinking lying is always wrong',
		"Smelling people's feet",
		"Saving someone's feet pics",
		'Taking a saucy photo of yourself',
		'Having a fursona',
		'Being in a romantic relationship',
		'Being bitchless',
		'Believing in fate or destiny',
		'Fear of spiders (or my wife coming back)',
		'Considering yourself a good person',
		'Ditching school',
		'Being told your zipper is down in public',
		'Returning a gift you acted like you loved',
		'Shuffling a deck of cards',
		'Creating a fake account to spy on people',
		"Being called 'insecure'",
		'Trying to ✨measure✨ yourself',
		'Crying in public',
		'Dining and dashing',
		'Using a dating app',
		'Dating someone younger than you',
		'Being in a fight',
		'Clogging a public toilet',
		"Using someone else's toothbrush on purpose",
		'Planning a fake text to leave an event',
		'Being attracted to a cartoon character',
		'Biting your toenails',
		'Getting stitches',
		'Trying to ride an animal',
		'Pretending to wear glasses',
		'Being trapped in an elevator',
		'Being in a talent show',
		"Accidentally saying 'I love you'",
		"Crushing on a friend's parent",
		'Lying about a death to get out of something',
		'Sleeping in a bathtub or shower',
		'Learning a second language',
		'Getting slapped',
		'Lying during an interview',
		'Catfishing or being catfished',
		'Being in an ambulance',
		'Watching the same movie twice in one day',
		'Assembling IKEA furniture'
	];

	let ideaTimeout;
	function generateIdea() {
		idea = ideas[Math.floor(Math.random() * ideas.length)];
		clearTimeout(ideaTimeout);
		ideaTimeout = setTimeout(() => {
			idea = '';
		}, 3000);
	}
</script>

<button
	class="mb-2 flex w-full items-center justify-center rounded-lg bg-linear-to-b from-indigo-400 to-indigo-600 p-2 shadow-md transition-all duration-200 hover:cursor-pointer hover:from-indigo-500 hover:to-indigo-700 md:w-2/3"
	bind:this={ideaButton}
	onclick={generateIdea}
>
	<h1>
		<span class="text-lg text-gray-100">Inspiration Button</span>
	</h1>
</button>

{#if idea}
	<Popup
		message={idea}
		x={ideaButton.offsetLeft}
		y={ideaButton.offsetTop - ideaButton.offsetHeight - 10}
	/>
{/if}
